### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by CherryLover** [ppd324/FaceIdentificationAndroid#1]
你好，我 clone 了你的 代码，但是无法正常编译，始终提示以下错误。

```
fatal error: 'opencv2/opencv.hpp' file not found
```

这个是缺少 opencv.hpp 的文件，这个文件是需要我电脑上安装上 OpenCV 吗？还是怎么获取到这个文件？

**Comment by ppd324** [comment]
是的，需要安装OpenCV-android-sdk

**Comment by CherryLover** [comment]
感谢，已解决。

解决方案：
在 app module 的 CMakeLists.txt 文件中需要配置自己电脑上的 Open cv 路径。例如

`set(pathToOpenCv /Users/jiangjiwei/Downloads/OpenCV-android-sdk/)`

opencv sdk 下载地址：https://opencv.org/releases/

解压后的文件结构

![解压后的文件结构](https://github.com/ppd324/FaceIdentificationAndroid/assets/18376501/a9fa9459-065e-4281-b9cd-bd0c4afc9f0d)
